CREATE TABLE "game_version" (
  "game_version_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "short_name" text,
  PRIMARY KEY ("game_version_id")
);

CREATE TABLE "character" (
  "character_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("character_id")
);

CREATE TABLE "engine_class" (
  "engine_class_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("engine_class_id")
);

CREATE TABLE "vehicle_option" (
  "vehicle_option_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("vehicle_option_id")
);

CREATE TABLE "vehicle" (
  "vehicle_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("vehicle_id")
);

CREATE TABLE "wheel" (
  "wheel_id" int GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("wheel_id")
);

CREATE TABLE "glider" (
  "glider_id" int GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("glider_id")
);

CREATE TABLE "course_selection" (
  "course_selection_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("course_selection_id")
);

CREATE TABLE "item_rule" (
  "item_rule_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("item_rule_id")
);

CREATE TABLE "cpu_difficulty" (
  "cpu_difficulty_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("cpu_difficulty_id")
);

CREATE TABLE "session" (
  "session_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "no_players" int NOT NULL,
  "game_version_id" int NOT NULL,
  "play_date" timestamp with time zone NOT NULL,
  "is_complete" bool DEFAULT (false),
  "no_races" int NOT NULL,
  "engine_class_id" int NOT NULL,
  "teams" int NOT NULL,
  "item_rule_id" int NOT NULL,
  "cpu_difficulty_id" int NOT NULL,
  "vehicle_option_id" int,
  "course_selection_id" int NOT NULL,
  "image_name" text,
  PRIMARY KEY ("session_id")
);

CREATE TABLE "player" (
  "player_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  PRIMARY KEY ("player_id")
);

CREATE TABLE "player_default" (
  "player_default_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "player_id" int NOT NULL,
  "game_version_id" int NOT NULL,
  "character_id" int,
  "vehicle_id" int,
  "wheel_id" int,
  "glider_id" int,
  PRIMARY KEY ("player_default_id")
);

CREATE TABLE "player_session" (
  "player_session_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "session_id" int NOT NULL,
  "player_id" int NOT NULL,
  "character_id" int NOT NULL,
  "vehicle_id" int NOT NULL,
  "wheel_id" int,
  "glider_id" int,
  PRIMARY KEY ("player_session_id")
);

CREATE TABLE "track" (
  "track_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "game_version_id" int NOT NULL,
  PRIMARY KEY ("track_id")
);

CREATE TABLE "race" (
  "race_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "session_id" int NOT NULL,
  "race_no" int NOT NULL,
  "start_track_id" int NOT NULL,
  "end_track_id" int,
  PRIMARY KEY ("race_id")
);

CREATE TABLE "position" (
  "position_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "game_version_id" int NOT NULL,
  "position" int NOT NULL,
  "points" int NOT NULL,
  PRIMARY KEY ("position_id")
);

CREATE TABLE "race_result" (
  "race_result_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "race_id" int NOT NULL,
  "player_session_id" int NOT NULL,
  "position_id" int NOT NULL,
  PRIMARY KEY ("race_result_id")
);

CREATE UNIQUE INDEX "nk_game_version" ON "game_version" ("name");

CREATE UNIQUE INDEX "nk_character" ON "character" ("game_version_id", "name");

CREATE UNIQUE INDEX "nk_engine_class" ON "engine_class" ("game_version_id", "name");

CREATE UNIQUE INDEX "nk_vehicle" ON "vehicle" ("game_version_id", "name");

CREATE UNIQUE INDEX "nk_wheel" ON "wheel" ("game_version_id", "name");

CREATE UNIQUE INDEX "nk_glider" ON "glider" ("game_version_id", "name");

CREATE UNIQUE INDEX "nk_course_selection" ON "course_selection" ("name", "game_version_id");

CREATE UNIQUE INDEX "nk_item_rule" ON "item_rule" ("name", "game_version_id");

CREATE UNIQUE INDEX "nk_cpu_difficulty" ON "cpu_difficulty" ("name", "game_version_id");

CREATE UNIQUE INDEX "nk_player" ON "player" ("name");

CREATE UNIQUE INDEX "nk_player_default" ON "player_default" ("player_id", "game_version_id");

CREATE UNIQUE INDEX "nk_player_session" ON "player_session" ("session_id", "player_id");

CREATE UNIQUE INDEX "nk_track" ON "track" ("name", "game_version_id");

CREATE UNIQUE INDEX "nk_race" ON "race" ("session_id", "race_no");

CREATE UNIQUE INDEX "nk_position" ON "position" ("game_version_id", "position");

CREATE UNIQUE INDEX "nk_race_result" ON "race_result" ("race_id", "player_id");

COMMENT ON TABLE "game_version" IS 'Stores the Mario Kart versions that are available in the app';

COMMENT ON COLUMN "game_version"."game_version_id" IS 'Primary key';

COMMENT ON COLUMN "game_version"."name" IS 'The name of the game, e.g. ''Mario Kart 8 Deluxe''';

COMMENT ON COLUMN "game_version"."short_name" IS 'Short name of the game, used for coding purposes, eg. ''mk8''';

COMMENT ON TABLE "character" IS 'Stores the characters that may be selected by the player during session setup.';

COMMENT ON COLUMN "character"."character_id" IS 'Primary key';

COMMENT ON COLUMN "character"."name" IS 'The name of the character';

COMMENT ON COLUMN "character"."game_version_id" IS 'The game version in which this character appears. Needed for filtering which options are available';

COMMENT ON TABLE "engine_class" IS 'Stores the engine classes that may be selected by the player during session setup.';

COMMENT ON COLUMN "engine_class"."engine_class_id" IS 'Primary key';

COMMENT ON COLUMN "engine_class"."name" IS 'The name of the engine class (50cc, 100cc, etc.)';

COMMENT ON COLUMN "engine_class"."game_version_id" IS 'The game version in which this engine class appears. Needed for filtering which options are available';

COMMENT ON TABLE "vehicle_option" IS 'Stores the options for vehicle types of the CPU players. Only applies to Mario Kart 8 Deluxe';

COMMENT ON COLUMN "vehicle_option"."vehicle_option_id" IS 'Primary key';

COMMENT ON COLUMN "vehicle_option"."name" IS 'The name of the CPU vehicle option regime';

COMMENT ON COLUMN "vehicle_option"."game_version_id" IS 'The game version in which this vehicle option regime applies';

COMMENT ON TABLE "vehicle" IS 'Stores the names of vehicles that may be selected by the player during session setup.';

COMMENT ON COLUMN "vehicle"."vehicle_id" IS 'Primary key';

COMMENT ON COLUMN "vehicle"."name" IS 'The name of the vehicle';

COMMENT ON COLUMN "vehicle"."game_version_id" IS 'The game in which the vehicle appears';

COMMENT ON TABLE "wheel" IS 'Stores the names of various wheel options that may be selected by the player during session setup.
  
  This only applies to MK 8, but to allow for future expansion we will include the game version';

COMMENT ON COLUMN "wheel"."wheel_id" IS 'Primary key';

COMMENT ON COLUMN "wheel"."name" IS 'The name of the wheels';

COMMENT ON COLUMN "wheel"."game_version_id" IS 'The game version that this wheel is in.';

COMMENT ON TABLE "glider" IS 'Stores the names of various glider options that may be selected by the player during session setup
  
  This only applies to MK 8, but to allow for future expansion we will include the game version';

COMMENT ON COLUMN "glider"."glider_id" IS 'Primary key';

COMMENT ON COLUMN "glider"."name" IS 'The name of the glider';

COMMENT ON COLUMN "glider"."game_version_id" IS 'The game version that this glider is in.';

COMMENT ON TABLE "course_selection" IS 'Stores the course selection regimes that are available during session setup';

COMMENT ON COLUMN "course_selection"."course_selection_id" IS 'Primary key';

COMMENT ON COLUMN "course_selection"."name" IS 'The name of the course selection regime';

COMMENT ON COLUMN "course_selection"."game_version_id" IS 'The game version to which this regime applies. Needed for filtering.';

COMMENT ON TABLE "item_rule" IS 'Stores the item rule sets that are available during session setup. May include "custom", but doesn''t specify which items are included.';

COMMENT ON COLUMN "item_rule"."item_rule_id" IS 'Primary key';

COMMENT ON COLUMN "item_rule"."name" IS 'Name of the item rule set';

COMMENT ON COLUMN "item_rule"."game_version_id" IS 'The game version to which the rule set applies. Needed for filtering';

COMMENT ON TABLE "cpu_difficulty" IS 'Stores the cpu difficulty levels that are available during session setup';

COMMENT ON COLUMN "cpu_difficulty"."cpu_difficulty_id" IS 'Primary key';

COMMENT ON COLUMN "cpu_difficulty"."name" IS 'The name of the cpu difficulty level';

COMMENT ON COLUMN "cpu_difficulty"."game_version_id" IS 'The game version to which this difficulty level applies. Needed for filtering.';

COMMENT ON TABLE "session" IS 'The settings for a single VS Race session of Mario Kart. Not all settings apply to every version of the game. Does not apply to other race types (e.g. Grand Prix).

  Assumes that a session is incomplete until updated, and that a session only takes place on a single calendar day.';

COMMENT ON COLUMN "session"."session_id" IS 'Primary key';

COMMENT ON COLUMN "session"."no_players" IS 'The number of players that will be in this session';

COMMENT ON COLUMN "session"."game_version_id" IS 'The Mario Kart version that was played during this session';

COMMENT ON COLUMN "session"."play_date" IS 'The date-time at which the session was played';

COMMENT ON COLUMN "session"."is_complete" IS 'Whether the session was completed. False indicates either that the session is not finished or was finished early. Defaults to `false` then updated on completion';

COMMENT ON COLUMN "session"."no_races" IS 'The number of races that were selected to be played in the session (regardless of how many were actually completed)';

COMMENT ON COLUMN "session"."engine_class_id" IS 'The engine class selected for the session.';

COMMENT ON COLUMN "session"."teams" IS 'How many teams of racers were selected for this session. 0 indicates no teams.';

COMMENT ON COLUMN "session"."item_rule_id" IS 'The selected item rules for this session.';

COMMENT ON COLUMN "session"."cpu_difficulty_id" IS 'The CPU difficulty level selected for this session.';

COMMENT ON COLUMN "session"."vehicle_option_id" IS 'The types of vehicles that may be used by the CPU for this session. Applies to MK 8 Deluxe only.';

COMMENT ON COLUMN "session"."course_selection_id" IS 'The course selection regime selected for this session.';

COMMENT ON COLUMN "session"."image_name" IS 'The name of the image file showing the selections made';

COMMENT ON TABLE "player" IS 'Stores the names of players for whom to store results.';

COMMENT ON COLUMN "player"."player_id" IS 'Primary key';

COMMENT ON COLUMN "player"."name" IS 'Name of the player';

COMMENT ON TABLE "player_default" IS 'Favourite setups for a player. A player may have a single favourite setup for each version of Mario Kart. They do not have to make a selection for each option.';

COMMENT ON COLUMN "player_default"."player_default_id" IS 'Primary key';

COMMENT ON COLUMN "player_default"."player_id" IS 'The player to whom this default setup applies';

COMMENT ON COLUMN "player_default"."game_version_id" IS 'The game version to which this default setup applies';

COMMENT ON COLUMN "player_default"."character_id" IS 'The character seleted for the default setup';

COMMENT ON COLUMN "player_default"."vehicle_id" IS 'The vehicle selected for the default setup';

COMMENT ON COLUMN "player_default"."wheel_id" IS 'The wheels selected for the default setup. MK 8 Deluxe only';

COMMENT ON COLUMN "player_default"."glider_id" IS 'The glider selected for the default setup. MK 8 Deluxe only';

COMMENT ON TABLE "player_session" IS 'Selections made by a player during session setup. Selections from the `player_default` table will be re-entered, rather than inserting a reference.';

COMMENT ON COLUMN "player_session"."player_session_id" IS 'Primary key';

COMMENT ON COLUMN "player_session"."session_id" IS 'The session to which this setup applies.';

COMMENT ON COLUMN "player_session"."player_id" IS 'The player to which this setup applies.';

COMMENT ON COLUMN "player_session"."character_id" IS 'The character selected by the player in this session.';

COMMENT ON COLUMN "player_session"."vehicle_id" IS 'The vehicle selected by the player in this session.';

COMMENT ON COLUMN "player_session"."wheel_id" IS 'The wheels selected by the player for this session. MK 8 only.';

COMMENT ON COLUMN "player_session"."glider_id" IS 'The glider selected by the player for this session. MK 8 only.';

COMMENT ON TABLE "track" IS 'Stores the names of tracks to be played during a session.';

COMMENT ON COLUMN "track"."track_id" IS 'Primary key';

COMMENT ON COLUMN "track"."name" IS 'The name of the track';

COMMENT ON COLUMN "track"."game_version_id" IS 'The game version containing this track. Used for filtering.';

COMMENT ON TABLE "race" IS 'Stores the details of each race within a session. 
  
  For Mario Kart 8, only `start_track_id` should be completed. For Mario Kart World, `end_track_id` may be null (indicates that it was a single-track race).';

COMMENT ON COLUMN "race"."race_id" IS 'Primary key';

COMMENT ON COLUMN "race"."session_id" IS 'The session of which the race is a part';

COMMENT ON COLUMN "race"."race_no" IS 'The race number within the session';

COMMENT ON COLUMN "race"."start_track_id" IS 'The starting track of the race (MK World) or the track on which the race is done (MK 8)';

COMMENT ON COLUMN "race"."end_track_id" IS 'The ending track of the race. MK World only.';

COMMENT ON TABLE "position" IS 'Stores the scores allocated to each position for each version of the game.';

COMMENT ON COLUMN "position"."position_id" IS 'Primary key';

COMMENT ON COLUMN "position"."game_version_id" IS 'The version of the game to which this result applies';

COMMENT ON COLUMN "position"."position" IS 'The ordinal position';

COMMENT ON COLUMN "position"."points" IS 'The number of points received from this position';

COMMENT ON TABLE "race_result" IS 'Stores the results of races for each player. Given that positions are tied to points, a foreign key relationship is required.';

COMMENT ON COLUMN "race_result"."race_result_id" IS 'Primary key';

COMMENT ON COLUMN "race_result"."race_id" IS 'The race for which this result is for';

COMMENT ON COLUMN "race_result"."player_session_id" IS 'The player-session for which this result is for';

COMMENT ON COLUMN "race_result"."position_id" IS 'The position in which the player finished.';

ALTER TABLE "character" ADD CONSTRAINT "fk_character_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "engine_class" ADD CONSTRAINT "fk_engine_class_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle_option" ADD CONSTRAINT "fk_vehicle_option_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vehicle" ADD CONSTRAINT "fk_vehicle_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wheel" ADD CONSTRAINT "fk_wheel_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "glider" ADD CONSTRAINT "fk_glider_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_selection" ADD CONSTRAINT "fk_course_selecion_for_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_rule" ADD CONSTRAINT "fk_item_rule_for_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cpu_difficulty" ADD CONSTRAINT "fk_difficulty_for_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_session_of_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_cc_of_session" FOREIGN KEY ("engine_class_id") REFERENCES "engine_class" ("engine_class_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_course_selection_of_session" FOREIGN KEY ("course_selection_id") REFERENCES "course_selection" ("course_selection_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_item_rule_of_session" FOREIGN KEY ("item_rule_id") REFERENCES "item_rule" ("item_rule_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_cpu_difficulty_of_session" FOREIGN KEY ("cpu_difficulty_id") REFERENCES "cpu_difficulty" ("cpu_difficulty_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_vehicle_option_of_session" FOREIGN KEY ("vehicle_option_id") REFERENCES "vehicle_option" ("vehicle_option_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_default" ADD CONSTRAINT "fk_player_default_for_player" FOREIGN KEY ("player_id") REFERENCES "player" ("player_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_default" ADD CONSTRAINT "fk_player_default_for_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_default" ADD CONSTRAINT "fk_character_selected_for_player_default" FOREIGN KEY ("character_id") REFERENCES "character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_default" ADD CONSTRAINT "fk_vehicle_selected_for_player_default" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle" ("vehicle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_default" ADD CONSTRAINT "fk_wheel_selected_for_player_default" FOREIGN KEY ("wheel_id") REFERENCES "wheel" ("wheel_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_default" ADD CONSTRAINT "fk_glider_selected_for_player_default" FOREIGN KEY ("glider_id") REFERENCES "glider" ("glider_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_session" ADD CONSTRAINT "fk_player_in_player_session" FOREIGN KEY ("player_id") REFERENCES "player" ("player_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_session" ADD CONSTRAINT "fk_session_in_player_session" FOREIGN KEY ("session_id") REFERENCES "session" ("session_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_session" ADD CONSTRAINT "fk_character_selected_for_player_session" FOREIGN KEY ("character_id") REFERENCES "character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_session" ADD CONSTRAINT "fk_vehicle_selected_for_player_session" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle" ("vehicle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_session" ADD CONSTRAINT "fk_wheel_selected_for_player_session" FOREIGN KEY ("wheel_id") REFERENCES "wheel" ("wheel_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_session" ADD CONSTRAINT "fk_glider_selected_for_player_session" FOREIGN KEY ("glider_id") REFERENCES "glider" ("glider_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track" ADD CONSTRAINT "fk_track_in_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "race" ADD CONSTRAINT "fk_race_in_session" FOREIGN KEY ("session_id") REFERENCES "session" ("session_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "race" ADD CONSTRAINT "fk_start_race_on_track" FOREIGN KEY ("start_track_id") REFERENCES "track" ("track_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "race" ADD CONSTRAINT "fk_end_race_on_track" FOREIGN KEY ("end_track_id") REFERENCES "track" ("track_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "position" ADD CONSTRAINT "fk_position_for_game_version" FOREIGN KEY ("game_version_id") REFERENCES "game_version" ("game_version_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "race_result" ADD CONSTRAINT "fk_race_result_for_race" FOREIGN KEY ("race_id") REFERENCES "race" ("race_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "race_result" ADD CONSTRAINT "fk_race_result_for_player" FOREIGN KEY ("player_session_id") REFERENCES "player_session" ("player_session_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "race_result" ADD CONSTRAINT "fk_position_for_race_result" FOREIGN KEY ("position_id") REFERENCES "position" ("position_id") DEFERRABLE INITIALLY IMMEDIATE;
