# Generated by Django 6.0.5 on 2026-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the character')),
            ],
            options={
                'db_table': 'character',
                'db_table_comment': 'Stores the characters that may be selected by the player during session setup.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('course_selection_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the course selection regime')),
            ],
            options={
                'db_table': 'course_selection',
                'db_table_comment': 'Stores the course selection regimes that are available during session setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpuDifficulty',
            fields=[
                ('cpu_difficulty_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the cpu difficulty level')),
            ],
            options={
                'db_table': 'cpu_difficulty',
                'db_table_comment': 'Stores the cpu difficulty levels that are available during session setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineClass',
            fields=[
                ('engine_class_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the engine class (50cc, 100cc, etc.)')),
            ],
            options={
                'db_table': 'engine_class',
                'db_table_comment': 'Stores the engine classes that may be selected by the player during session setup.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('game_version_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment="The name of the game, e.g. 'Mario Kart 8 Deluxe'", unique=True)),
            ],
            options={
                'db_table': 'game_version',
                'db_table_comment': 'Stores the Mario Kart versions that are available in the app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glider',
            fields=[
                ('glider_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the glider', unique=True)),
            ],
            options={
                'db_table': 'glider',
                'db_table_comment': 'Stores the names of various glider options that may be selected by the player during session setup\n  \n  This only applies to MK 8, hence why the game version is not recorded',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemRule',
            fields=[
                ('item_rule_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='Name of the item rule set')),
            ],
            options={
                'db_table': 'item_rule',
                'db_table_comment': 'Stores the item rule sets that are available during session setup. May include "custom", but doesn\'t specify which items are included.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='Name of the player', unique=True)),
            ],
            options={
                'db_table': 'player',
                'db_table_comment': 'Stores the names of players for whom to store results.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerDefault',
            fields=[
                ('player_default_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'player_default',
                'db_table_comment': 'Favourite setups for a player. A player may have a single favourite setup for each version of Mario Kart. They do not have to make a selection for each option.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('player_session_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'player_session',
                'db_table_comment': 'Selections made by a player during session setup. Selections from the `player_default` table will be re-entered, rather than inserting a reference.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('position', models.IntegerField(db_comment='The ordinal position')),
                ('points', models.IntegerField(db_comment='The number of points received from this position')),
            ],
            options={
                'db_table': 'position',
                'db_table_comment': 'Stores the scores allocated to each position for each version of the game.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('race_no', models.IntegerField(db_comment='The race number within the session')),
            ],
            options={
                'db_table': 'race',
                'db_table_comment': 'Stores the details of each race within a session. \n  \n  For Mario Kart 8, only `start_track_id` should be completed. For Mario Kart World, `end_track_id` may be null (indicates that it was a single-track race).',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('race_result_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'race_result',
                'db_table_comment': 'Stores the results of races for each player. Given that positions are tied to points, a foreign key relationship is required."',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('no_players', models.IntegerField(db_comment='The number of players that will be in this session')),
                ('play_date', models.DateTimeField(db_comment='The date-time at which the session was played')),
                ('is_complete', models.BooleanField(blank=True, db_comment='Whether the session was completed. False indicates either that the session is not finished or was finished early. Defaults to `false` then updated on completion', null=True)),
                ('no_races', models.IntegerField(db_comment='The number of races that were selected to be played in the session (regardless of how many were actually completed)')),
                ('teams', models.IntegerField(db_comment='How many teams of racers were selected for this session. 0 indicates no teams.')),
                ('vehicle_selection', models.TextField(blank=True, db_comment='The types of vehicles that may be used by the CPU for this session. Applies to MK 8 Deluxe only.', null=True)),
                ('image_name', models.TextField(blank=True, db_comment='The name of the image file showing the selections made', null=True)),
            ],
            options={
                'db_table': 'session',
                'db_table_comment': 'The settings for a single VS Race session of Mario Kart. Not all settings apply to every version of the game. Does not apply to other race types (e.g. Grand Prix).\n\n  Assumes that a session is incomplete until updated, and that a session only takes place on a single calendar day.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the track')),
            ],
            options={
                'db_table': 'track',
                'db_table_comment': 'Stores the names of tracks to be played during a session.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the vehicle')),
            ],
            options={
                'db_table': 'vehicle',
                'db_table_comment': 'Stores the names of vehicles that may be selected by the player during session setup.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('wheel_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='The name of the wheels', unique=True)),
            ],
            options={
                'db_table': 'wheel',
                'db_table_comment': 'Stores the names of various wheel options that may be selected by the player during session setup.\n  \n  This only applies to MK 8, hence why the game version is not recorded',
                'managed': False,
            },
        ),
    ]
