# Generated by Django 6.0.5 on 2026-05-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mario_kart_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseselection',
            options={'managed': False, 'verbose_name_plural': 'Course Selection Regimes'},
        ),
        migrations.AlterModelOptions(
            name='cpudifficulty',
            options={'managed': False, 'verbose_name_plural': 'CPU Difficulty Levels'},
        ),
    ]
