# Generated by Django 6.0.5 on 2026-06-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mario_kart_tracker', '0002_alter_courseselection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='glider',
            table_comment='Stores the names of various glider options that may be selected by the player during session setup\n  \n  This only applies to MK 8, but to allow for future expansion we will include the game version',
        ),
        migrations.AlterModelTableComment(
            name='wheel',
            table_comment='Stores the names of various wheel options that may be selected by the player during session setup.\n  \n  This only applies to MK 8, but to allow for future expansion we will include the game version',
        ),
    ]
